# Generated by Django 5.2.7 on 2025-11-19 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photopost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos', verbose_name='動画'),
        ),
    ]
