# Generated by Django 5.2.7 on 2025-11-19 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('make', '0002_photopost_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photopost',
            old_name='imagel',
            new_name='image1',
        ),
    ]
