# Generated by Django 5.2.7 on 2025-11-25 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make', '0003_rename_imagel_photopost_image1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photopost',
            name='comment',
        ),
        migrations.AddField(
            model_name='photopost',
            name='comment_1',
            field=models.TextField(blank=True, null=True, verbose_name='コメント1'),
        ),
        migrations.AddField(
            model_name='photopost',
            name='comment_2',
            field=models.TextField(blank=True, null=True, verbose_name='コメント2'),
        ),
    ]
